# For more information: https://laravel.com/docs/sail
version: "3"
services:
  laravel:
    build:
      context: ./docker-public/
      dockerfile: Dockerfile
    # image: c7php80apache-public_html:latest
    ports:
      - '8090:80'
    volumes:
      - '.:/home/homepage/'
    depends_on:
      - mysql
      - mailhog
    privileged: true
    working_dir: /home/homepage/
  mysql:
    image: "mysql:8.0"
    ports:
      - "${FORWARD_DB_PORT:-3310}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_TCP_PORT: 3310
    volumes:
      - "dbdata:/var/lib/mysql"
    # networks:
    #     - sailaa
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
    # redis:
    #     image: "redis:alpine"
    #     ports:
    #         - "${FORWARD_REDIS_PORT:-6379}:6379"
    #     volumes:
    #         - "sailredis:/data"
    #     networks:
    #         - sailaa
    #     healthcheck:
    #         test: ["CMD", "redis-cli", "ping"]
    #         retries: 3
    #         timeout: 5s
    # meilisearch:
    #     image: 'getmeili/meilisearch:latest'
    #     platform: linux/x86_64
    #     ports:
    #         - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    #     volumes:
    #         - 'sailmeilisearch:/data.ms'
    #     networks:
    #         - sailaa
    #     healthcheck:
    #         test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
    #         retries: 3
    #         timeout: 5s
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1026}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8026}:8025'
        # networks:
        #     - sailaa
    # selenium:
    #     image: 'selenium/standalone-chrome'
    #     volumes:
    #         - '/dev/shm:/dev/shm'
    #     networks:
    #         - sailaa
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    ports:
      - "2223:80"
    environment:
      PMA_HOST: "${DB_HOST}"
      PMA_PORT: "${DB_PORT:-3310}"
    depends_on:
      - mysql
volumes:
  dbdata:
    driver: local
    # sailredis:
    #     driver: local
    # sailmeilisearch:
    #     driver: local
