version: '3'
services:
  laravel:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT:-8080}:80'
    working_dir: /home/homepage
    volumes:
      - '.:/home/homepage'
    depends_on:
      - mysql
      # - redis
      # - meilisearch
      # - selenium
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${DB_PORT:-13306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_TCP_PORT: '${DB_PORT}'
    expose:
      - ${DB_PORT}
    volumes:
      - 'sailmysql:/var/lib/mysql'
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-p${DB_PASSWORD}' ]
      retries: 3
      timeout: 5s
  # redis:
  #     image: "redis:alpine"
  #     ports:
  #         - "${FORWARD_REDIS_PORT:-6379}:6379"
  #     volumes:
  #         - "sailredis:/data"
  #     healthcheck:
  #         test: ["CMD", "redis-cli", "ping"]
  #         retries: 3
  #         timeout: 5s
  # meilisearch:
  #     image: 'getmeili/meilisearch:latest'
  #     platform: linux/x86_64
  #     ports:
  #         - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
  #     volumes:
  #         - 'sailmeilisearch:/data.ms'
  #     healthcheck:
  #         test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
  #         retries: 3
  #         timeout: 5s

  # mailhog:
  #   image: 'mailhog/mailhog:latest'
  #   ports:
  #     - '${FORWARD_MAILHOG_PORT:-1025}:1025'
  #     - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'

  # selenium:
  #   image: 'selenium/standalone-chrome'
  #   volumes:
  #     - '/dev/shm:/dev/shm'
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    ports:
      - '12222:80'
    environment:
      PMA_HOST: '${DB_HOST}'
      PMA_PORT: '${DB_PORT}'
    depends_on:
      - mysql
# networks:
#   sailaa:
#     driver: bridge
volumes:
  sailmysql:
    driver: local
  # sailredis:
  #     driver: local
  # sailmeilisearch:
  #     driver: local
